version: "3.8"
services:
  vault:
    image: vault
    container_name: pvault
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
    environment:
#      change to your address
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json